# Generated by Django 2.2.1 on 2021-11-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('-create_time',), 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
