# Generated by Django 2.2.1 on 2021-11-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20211126_2222'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articlepost',
            table='articlepost',
        ),
    ]
