# Generated by Django 2.2.12 on 2021-11-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20211126_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='auther',
            new_name='author',
        ),
    ]
